
services:  
  mysql:
    image: mysql:8.0.39
    restart: always
    container_name: db-teg-test1
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
